#!/usr/bin/env ruby

filenames = Dir.entries('files').select{ |filename| !['.', '..'].include?(filename) }

unless File.exist?(File.expand_path('~/.vim/autoload/plug.vim'))
  `curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim`
end

filenames.each do |filename|
  puts "symlinking #{filename}... \n"
  symlink = File.join(Dir.home, ".#{filename}")
  `mv #{symlink} #{symlink}.bkp`
  puts File.join(Dir.home, 'dotfiles', 'files', filename)
  `ln -s #{File.join(Dir.home, 'dotfiles', 'files', filename)} #{symlink}`
end

# create folders needed for packages like npm
`mkdir #{File.join(Dir.home, '.npm-packages')}`
