#!/usr/bin/env ruby

filenames = Dir.entries('files').select{ |filename| !['.', '..'].include?(filename) }

filenames.each do |filename|
  puts "symlinking #{filename}... \n"
  symlink = "~/.#{filename}"
  `mv #{symlink} #{symlink}.bkp`
  puts File.join(Dir.home, 'dotfiles', 'files', filename)
  `ln -s #{File.join(Dir.home, 'dotfiles', 'files', filename)} #{symlink}`
end
