source ~/.bashrc

# my stuff
if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi

# User specific aliases and functions
alias gp='git pull; git submodule update'
alias dlog='tail -f log/development.log'
# load tmux with 256 colors support (for vim)
alias tmux='tmux -2'
# simple http server
alias server='python -m SimpleHTTPServer'
alias ll='ls -lG'
alias sniff='curl -w "@$HOME/.sniff.txt" -o /dev/null -s '

unamestring=`uname`
 
# in order to deal with nginx on linux (apt-get) and osx (homebrew)
if [[ "$unamestring" == 'Darwin' ]]; then
  alias nxstart='sudo nginx -s stop; echo "starting nginx..."; sudo nginx'
  alias ctags="`brew --prefix`/bin/ctags"
elif [[ "$unamestring" == 'Linux' ]]; then
  alias nxstart='sudo service nginx stop; sudo service nginx start'
fi


function mega()
{
  if [ -n "$1" ] # branch name passed
    then
      git co "$1"
  fi
  gp; bundle install; rake db:migrate
}

# let's search for a string and open the results in vim!!!
# params: 
#   $1: string to search
#   $2: search path (default to .)
# TODO: Pass line number to vim
function age()
{
  ag $1 --no-numbers -l $2 |xargs vim
}

export PATH="$HOME/.npm-packages/bin:$PATH"

export PATH="/usr/local/sbin:$PATH"

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

# prompt is getting override somewhere... let's source it here
source ~/.prompt
