source ~/.bashrc

# my stuff
if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi

# User specific aliases and functions
alias gp='git pull; git submodule update'
alias dlog='tail -f log/development.log'
alias tlog='tail -f log/test.log'
# load tmux with 256 colors support (for vim)
alias tmux='tmux -2'
# simple http server
alias server='python -m SimpleHTTPServer'
alias ll='ls -lG'
alias sniff='curl -w "@$HOME/.sniff.txt" -o /dev/null -s '
alias rubocop='rubocop -c ~/.rubocop.yml'
alias rc='DISABLE_PRY_RAILS=1 rails c'
alias t='todo.sh -d ~/.todo.cfg'

unamestring=`uname`
 
# osx aliases / linux aliases
if [[ "$unamestring" == 'Darwin' ]]; then
  alias nxstart='sudo nginx -s stop; echo "starting nginx..."; sudo nginx'
  alias ctags="`brew --prefix`/bin/ctags"
elif [[ "$unamestring" == 'Linux' ]]; then
  alias nxstart='sudo service nginx stop; sudo service nginx start'
fi


function mega()
{
  if [ -n "$1" ] # branch name passed
    then
      git co "$1"
  fi
  gp; bundle install; rake db:migrate; rake db:migrate RAILS_ENV=test
}

# new feature branch from current branch
function newf()
{
  git co -b feature/#"$1"; git push -u origin feature/#"$1"
}

# new bug branch from current branch
function newb()
{
  git co -b bug/#"$1"; git push -u origin bug/#"$1"
}

export PATH="$HOME/.npm-packages/bin:$PATH"

export PATH="/usr/local/sbin:$PATH"

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

export PATH="$PATH:$(go env GOPATH)/bin"

export GPG_TTY=$(tty)

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

# prompt is getting override somewhere... let's source it here
source ~/.prompt
