#!/usr/bin/env ruby

# By Uğur Özyılmazel, @vigobronx | @ugurozyilmazel
# http://vigodome.com | http://ugur.ozyilmazel.com | http://github.com/vigo

def get_paged_memory_usage(match_string, paging=4096)
  mvar =
    if match_string.split(/[^\w]/).length > 1
      4
    else
      3
    end

  paged_val = `vm_stat | grep "Pages #{match_string}:" | awk '{ print $#{mvar}}'`.to_i
  gigabyte_val = (paged_val * paging) / 1024 / 1024 / 1000.0
end

installed_memory = `sysctl -n hw.memsize`.to_i / 1024 / 1024 / 1000.0
total_consumed =
  ['wired down', 'active', 'inactive'].reduce(0) { |sum, key| sum + get_paged_memory_usage(key) }

printf('%.2f GB', (installed_memory - total_consumed)) # returns in gigabytes
