#!/usr/bin/env ruby

class WhatsPlaying
  attr_accessor :app

  def initialize(app)
    self.app = app
  end

  def self.status(app)
    new(app).status
  end

  def status
    return "this script is meant to run on macOS/OSX, sorry" unless mac?
    return "(#{app}) idle" unless running?

    "(#{app}) #{playing_status}: #{artist} - #{song}" if artist != '' && song != ''
  end

  private

  def running?
    # How to ps without adding command to results:
    # https://unix.stackexchange.com/a/74186
    `ps -ax |ag "[/]Applications/#{app}.app/Contents/MacOS/#{app}"`.split("\n").size >= 1
  end

  def mac?
    !(/darwin/ =~ RUBY_PLATFORM).nil?
  end

  def get_status(field)
    `osascript -e 'tell application "#{app}" to #{field} of current track as string'`.chop
  end

  def artist
    @artist ||= get_status('artist')
  end

  def song
    @song ||= get_status('name')
  end

  def playing_status
    @playing_status ||= `osascript -e 'tell application "#{app}" to player state as string'`.chop.capitalize
  end
end

puts "#{WhatsPlaying.status('Music')} | #{WhatsPlaying.status('Spotify')}"
