filetype plugin indent on    " Enable filetype-specific plugins, filetype-specific indenting
syntax on             " Enable syntax highlighting

let mapleader = ","

set encoding=utf-8
set autoindent
set showcmd
set wildmenu
set wildmode=list:longest
set title
set ruler
set hlsearch
set incsearch
set showmatch
set ignorecase
set smartcase
set hidden
set number
set hlsearch
set history=1000
set autoread
set undolevels=1000
set termguicolors

" nvim 0.8.0 activates the damn mouse by default :/
set mouse=

set backupdir=/tmp   
set directory=/tmp// "don't clutter my dirs with swp and tmp files

set backspace=indent,eol,start
set softtabstop=2
set shiftwidth=2
set expandtab
set background=dark
set foldmethod=indent
set nrformats=
set foldlevel=9999

highlight StatusLine ctermfg=yellow

" switch windows with <leader> w
nmap <leader>w <C-w><C-w>

" Quickly edit/reload the vimrc file
nmap <silent> <leader>ev :e $MYVIMRC<CR>
nmap <silent> <leader>sv :so $MYVIMRC<CR>

" clear highlighting
map <C-h> :nohl<CR>

" ctrl-s to save
map <C-s> <esc>:w<CR>
imap <C-s> <esc>:w<CR>

"Reselect visual block after indent/outdent
vnoremap < <gv
vnoremap > >gv

" Split resizing
nnoremap <S-Up> <C-W>-<C-W>-
nnoremap <S-Down> <C-W>+<C-W>+
nnoremap <S-Left> <C-W>><C-W>>
nnoremap <S-Right> <C-W><<C-W><

if &term =~ '^screen'
  " tmux will send xterm-style keys when its xterm-keys option is on
  execute "set <xUp>=\e[1;*A"
  execute "set <xDown>=\e[1;*B"
  execute "set <xRight>=\e[1;*C"
  execute "set <xLeft>=\e[1;*D"
endif

" when to jump to the next line
if exists("&colorcolumn")
  set colorcolumn=80,100
endif

" change double to single quotes
nmap <leader>' cs"'

" change single to double quotes
nmap <leader>" cs"'

" allow semicolon to serve as colon
nnoremap ; :

" faster ways to get out of insert mode
imap ;; <esc>

" also works in visual mode
vmap ;; <esc>

" http://vimcasts.org/episodes/accessing-the-system-clipboard-from-vim/

" copy to OS clipboard.
nmap <leader>y "+y
vmap <leader>y "+y
nmap <leader>yy "+yy

" paste from OS clipboard
nmap <leader>p "+p
nmap <leader>P "+P
vmap <leader>p "+p
vmap <leader>P "+P"`"`"

" Format and then going back to where I was 
" https://www.reddit.com/r/vim/comments/7yzblt/what_was_your_best_vimrc_addition/dul39y7/
nnoremap g= mmgg=G`m
nnoremap gQ mmgggqG`m
